services:
  postgres:
    image: postgres:16
    container_name: car_maintenance_postgres
    environment:
      POSTGRES_DB: car_maintenance
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_pass
    ports:
      - "5432:5432"
    volumes:
      - car_maintenance_pgdata:/var/lib/postgresql/data

volumes:
  car_maintenance_pgdata:
